# Generated by Django 5.0.6 on 2024-05-20 20:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('bicycles_owned', models.SmallIntegerField(default=0)),
                ('unicycles_owned', models.SmallIntegerField(default=0)),
                ('tricycles_owned', models.SmallIntegerField(default=0)),
                ('mountain_bikes_owned', models.SmallIntegerField(default=0)),
                ('bmx_bikes_owned', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=100)),
                ('number_in_stock', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime(2024, 5, 20, 16, 14, 3, 652745))),
                ('number', models.SmallIntegerField(default=1)),
                ('paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_django_practice_app.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_django_practice_app.vehicle')),
            ],
        ),
    ]
